# Generated by Django 5.2.4 on 2025-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
