# Generated by Django 5.2.4 on 2025-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0002_herostats_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herostats',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
