# Generated by Django 5.2.4 on 2025-07-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0003_alter_herostats_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
