# Generated by Django 5.2.4 on 2025-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0004_herostats_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostats',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
