# Generated by Django 5.2.4 on 2025-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0005_herostats_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('bio', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('social', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
