# Generated by Django 5.2.4 on 2025-07-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0007_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='social',
        ),
    ]
