# Generated by Django 5.2.4 on 2025-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0010_aboutfeatures_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('price', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('deliveryTime', models.CharField(max_length=200)),
                ('projects', models.CharField(max_length=200)),
            ],
        ),
    ]
