# Generated by Django 5.2.4 on 2025-07-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0012_sociallinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
