# Generated by Django 5.2.4 on 2025-07-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcode', '0013_delete_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('features', models.JSONField(default=list)),
                ('popular', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
